### ISSUE TITLE
"ValueError: Invalid webhook URL provided."

### ISSUE THREAD

**Issue by dbva** [kyb3r/dhooks#50]
I tried following the exact same photo the tutorial showed me but it kept sending me errors, I've tried googling the error but nothing helped so far, I updated dhooks to version 1.1.4 and tried some other things but nothing worked.

Source code:
![image](https://user-images.githubusercontent.com/99571289/153737456-9dfe234e-5b9e-4e60-b00f-9dbdc8c162f2.png)

The error I keep getting:
![image](https://user-images.githubusercontent.com/99571289/153737480-18db6819-3050-4927-9474-bbd0171b3a41.png)

**Comment by TheLovinator1** [comment]
![Code_-_Insiders_WOOy5nB1Ay](https://user-images.githubusercontent.com/4153203/153743329-3aa84536-98b3-48b4-a379-a084cdd435a5.png)
![Discord_2g7wULi3Dn](https://user-images.githubusercontent.com/4153203/153743330-042cc26c-f74f-406a-b625-4f07f381223a.png)

Works for me ™️ 

Does your webhook start with https://discord.com or https://discordapp.com? It was fixed in 247fac5123a700dab789e69ac55ce99a89d95da9 but 1.1.4 is the commit before this one, so you need to change discordapp to discord.

**Comment by dbva** [comment]
> ![Code_-_Insiders_WOOy5nB1Ay](https://user-images.githubusercontent.com/4153203/153743329-3aa84536-98b3-48b4-a379-a084cdd435a5.png) ![Discord_2g7wULi3Dn](https://user-images.githubusercontent.com/4153203/153743330-042cc26c-f74f-406a-b625-4f07f381223a.png)
> 
> Works for me ™️
> 
> Does your webhook start with https://discord.com or https://discordapp.com? It was fixed in [247fac5](https://github.com/kyb3r/dhooks/commit/247fac5123a700dab789e69ac55ce99a89d95da9) but 1.1.4 is the commit before this one, so you need to change discordapp to discord.

Yeah, I've tried both discordapp.com and discord.com but none of them worked, I tried using a website that tests your webhook by sending a message with it, that worked but my original code still doesnt.

**Comment by TheLovinator1** [comment]
Welp, then I have no idea lol
I guess you have tried a fresh virtual environment?

**Comment by dbva** [comment]
> Welp, then I have no idea lol I guess you have tried a fresh virtual environment?

I've actually figured it out, I just reinstalled PyCharm and reinstalled all of the packages and now it worked, I guess there was some error with the app or something but thanks for helping anyways.
